recipe: default.v1
language: en
pipeline:
    - name: SpacyNLP
      model: "en_core_web_md"
    - name: SpacyTokenizer
    - name: CountVectorsFeaturizer
    - name: LanguageModelFeaturizer
      model_name: "bert"
      model_weights: "sentence-transformers/bert-base-nli-mean-tokens"
    - name: CountVectorsFeaturizer
      model_name: "bert"
      model_weights: "has-abi/bert-finetuned-resumes-sections"
    - name: RegexFeaturizer
    - name: LexicalSyntacticFeaturizer
    - name: CountVectorsFeaturizer
      analyzer: char_wb
      min_ngram: 1
      max_ngram: 4  
    - name: SpacyFeaturizer
      pooling: mean
    - name: SpacyEntityExtractor
      dimensions: ["PERSON", "LOC", "ORG", "PRODUCT", "LANGUAGE"]
    - name: CRFEntityExtractor
    - name: RegexEntityExtractor
      # text will be processed with case insensitive as default
      case_sensitive: False
      # use lookup tables to extract entities
      use_lookup_tables: True
      # use regexes to extract entities
      use_regexes: True
      # use match word boundaries for lookup table
      use_word_boundaries: True
    - name: EntitySynonymMapper
    - name: SklearnIntentClassifier
    - name: DIETClassifier
      epochs: 100
      num_transformer_layers: 4
      transformer_size: 256
      use_masked_language_model: True
      drop_rate: 0.25
      weight_sparsity: 0.7
      batch_size: [64, 256]
      embedding_dimension: 30
      hidden_layer_sizes:
        text: [512, 128]
    - name: ResponseSelector
      epochs: 100
      constrain_similarities: true
    - name: FallbackClassifier
      threshold: 0.3
      ambiguity_threshold: 0.1


policies:
  - name: AugmentedMemoizationPolicy
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true

